##### Where is the data? #####

basecalled_path: path/to/data
annotated_path: annotations
output_path: analysis

##### Mapping reference panel #####

references_file: "../../references.fasta"
amplicon_csv: "../../primer_file.csv"
bin_factor: 

##### Barcodes to process #####


##### Read length filtering range #####

min_read_length: 400
max_read_length: 2500

##### Read thresholds #####

min_reads: 20
min_pcent: 0

##### Analysis Stem #####
